import { createFeature } from './ui-module.js';
export const uiContribution = { ...{
        "title": "SQL",
        "slot": "architecture",
        "view": "sql",
        "fragments": [
            {
                "id": "architecture-panel-sql",
                "html": "<section id=\"architecture-panel-sql\" class=\"architecture-panel\" data-architecture-panel=\"sql\" role=\"tabpanel\" aria-labelledby=\"architecture-tab-sql\" hidden>\n          <form id=\"architecture-sql-form\" class=\"architecture-form\">\n            <label>\n              Metric\n              <input id=\"architecture-sql-metric\" type=\"text\" value=\"total_revenue\" autocomplete=\"off\">\n            </label>\n            <label>\n              Dimension\n              <input id=\"architecture-sql-dimension\" type=\"text\" value=\"data-column:orders:order_date\" autocomplete=\"off\">\n            </label>\n            <label>\n              Filter column\n              <input id=\"architecture-sql-filter-column\" type=\"text\" value=\"data-column:orders:status\" autocomplete=\"off\">\n            </label>\n            <label>\n              Filter value\n              <input id=\"architecture-sql-filter-value\" type=\"text\" value=\"paid\" autocomplete=\"off\">\n            </label>\n            <label>\n              Limit\n              <input id=\"architecture-sql-limit\" type=\"number\" min=\"1\" max=\"1000\" value=\"200\">\n            </label>\n            <div class=\"architecture-form-actions\">\n              <button id=\"architecture-sql-plan-btn\" class=\"primary\" type=\"submit\">Plan</button>\n              <button id=\"architecture-sql-approve-btn\" type=\"button\" disabled>Approve</button>\n              <button id=\"architecture-sql-execute-btn\" type=\"button\" disabled>Execute</button>\n            </div>\n          </form>\n          <div class=\"architecture-toolbar\">\n            <div id=\"architecture-sql-status\" class=\"architecture-status\" role=\"status\"></div>\n          </div>\n          <div id=\"architecture-sql-preview\" class=\"architecture-code\" aria-label=\"SQL preview\"></div>\n          <form id=\"architecture-sql-validation-form\" class=\"architecture-form architecture-sql-validation-form\">\n            <label class=\"full\">\n              SQL safety check\n              <textarea id=\"architecture-sql-validation-input\" rows=\"3\" spellcheck=\"false\">SELECT o.id FROM public.orders o CROSS JOIN public.orders other LIMIT 10</textarea>\n            </label>\n            <div class=\"architecture-form-actions\">\n              <button id=\"architecture-sql-validation-btn\" type=\"submit\">Validate SQL</button>\n            </div>\n          </form>\n          <div id=\"architecture-sql-validation-result\" class=\"architecture-sql-validation-result\" aria-live=\"polite\"></div>\n          <div id=\"architecture-sql-results\" class=\"architecture-results\" aria-live=\"polite\"></div>\n        </section>"
            }
        ]
    }, slot: 'architecture' as const, moduleSource: 'export const createFeature = ' + createFeature.toString() };
